### ISSUE TITLE
Document

### ISSUE THREAD

**Issue by AdwardAllan** [Riveryh/gpu-spectral-channel-DNS#1]
hello,there is no document for spaectral method , could you provides some details  for numericall method .Thanks

**Comment by Riveryh** [comment]
Hi Adward, the numerical method used in this code is mentioned in this papers,
https://link.springer.com/article/10.1007/s11433-018-9310-4
For time integration, it's basically a second-order Adams-Bashforth scheme for the non-linear term and a second-order Crank-Nicolson scheme fothe linear time. The spatial numerical scheme uses Fourier bases for spanwise and streamwsie along with periodical boundary conditions. For wall-normal direction, the chebyshev function is used for non-slip boundary condtion. The dialiasing method is 3/2 padding.

**Comment by AdwardAllan** [comment]
Hi Riveryh,  Think you very much.

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年8月2日 14:40
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Riveryh/gpu-spectral-channel-DNS] Document (Issue #1)


Hi Adward, the numerical method used in this code is mentioned in this papers,
https://link.springer.com/article/10.1007/s11433-018-9310-4
For time integration, it's basically a second-order Adams-Bashforth scheme for the non-linear term and a second-order Crank-Nicolson scheme fothe linear time. The spatial numerical scheme uses Fourier bases for spanwise and streamwsie along with periodical boundary conditions. For wall-normal direction, the chebyshev function is used for non-slip boundary condtion. The dialiasing method is 3/2 padding.

―
